version: "2"

services:
  db:
    image: mongo
    volumes:
      - db_data:/data
    restart: always
    expose:
      - "27017"

  api:
    depends_on:
      - db
    build: .
    env_file: .env
    restart: always
    environment:
      VIRTUAL_HOST: api.nakasar.me
      MONGO_URL: mongodb://db:27017/gw2rp
      PORT: 80

volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
