openapi: 3.0.0

info:
  title: GuildWars 2 RolePlay ToolBox
  description: A set of APIs to store events, activities and characters of roleplayers in Guild Wars 2 MMORPG.
  version: 0.0.0
  termsOfService: https://gw2rp-tools.ovh/terms/
  contact:
    name: GW2RP Tools Support
    url: https://gw2rp-tools.ovh/support
  license:
    name: MIT

tags:
  - name: authentication
  - name: admin
  - name: users
  - name: locations
  - name: events
  - name: rumors
  - name: characters
  - name: tools
  - name: others

paths:
  /auth:
    post:
      description: Authenticate and get a token.
      tags:
        - authentication
  /signup:
    post:
      description: Create a new user account.
      tags:
        - authentication

components:
  schemas:
    BasicResponse:
      type: object
      required:
      - success
      - message
      properties:
        message:
          type: string
        success:
          type: boolean
          example: true
    ErrorResponse:
      type: object
      required:
      - success
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          required:
          - message
          - id
          properties:
            message:
              type: string
            id:
              type: string
    User:
    Location:
    Event:
    Rumor:
